version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony_product_api?serverVersion=8.0"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
    command: >
      sh -c "
      composer install &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php bin/console messenger:setup-transports &&
      symfony server:start --no-tls --port=8000
      "

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_product_api
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_messenger
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony_product_api?serverVersion=8.0"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
    command: php bin/console messenger:consume async -vv

volumes:
  db_data: